// Generated by gencpp from file signal_processing/Signal.msg
// DO NOT EDIT!


#ifndef SIGNAL_PROCESSING_MESSAGE_SIGNAL_H
#define SIGNAL_PROCESSING_MESSAGE_SIGNAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace signal_processing
{
template <class ContainerAllocator>
struct Signal_
{
  typedef Signal_<ContainerAllocator> Type;

  Signal_()
    : value(0.0)
    , time(0.0)  {
    }
  Signal_(const ContainerAllocator& _alloc)
    : value(0.0)
    , time(0.0)  {
  (void)_alloc;
    }



   typedef double _value_type;
  _value_type value;

   typedef double _time_type;
  _time_type time;




  typedef boost::shared_ptr< ::signal_processing::Signal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::signal_processing::Signal_<ContainerAllocator> const> ConstPtr;

}; // struct Signal_

typedef ::signal_processing::Signal_<std::allocator<void> > Signal;

typedef boost::shared_ptr< ::signal_processing::Signal > SignalPtr;
typedef boost::shared_ptr< ::signal_processing::Signal const> SignalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::signal_processing::Signal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::signal_processing::Signal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace signal_processing

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'signal_processing': ['/home/mateusz/Pulpit/Robotic_Environment/lab10_ros_sigal_processing/catkin_ws/src/signal_processing/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::signal_processing::Signal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::signal_processing::Signal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::signal_processing::Signal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::signal_processing::Signal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::signal_processing::Signal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::signal_processing::Signal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::signal_processing::Signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba1a73d76a2ba457734934c938d2417f";
  }

  static const char* value(const ::signal_processing::Signal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba1a73d76a2ba457ULL;
  static const uint64_t static_value2 = 0x734934c938d2417fULL;
};

template<class ContainerAllocator>
struct DataType< ::signal_processing::Signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "signal_processing/Signal";
  }

  static const char* value(const ::signal_processing::Signal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::signal_processing::Signal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 value\n\
float64 time\n\
";
  }

  static const char* value(const ::signal_processing::Signal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::signal_processing::Signal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Signal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::signal_processing::Signal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::signal_processing::Signal_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<double>::stream(s, indent + "  ", v.value);
    s << indent << "time: ";
    Printer<double>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIGNAL_PROCESSING_MESSAGE_SIGNAL_H
